[package]
name = "hw5352"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
approx = "0.5.1"
csv = "1.1.6"
impl-trait-for-tuples = "0.2.2"
itertools = "0.10"
rand = "0.8.5"
clap = { version = "4.5.27", features = ["derive"] }
serde = { version = "1.0.137", features = ["derive"] }